CREATE TABLE IF NOT EXISTS Users(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL UNIQUE,
    Email TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    IsAdmin INTEGER NOT NULL DEFAULT 0,
    IsBanned INTEGER NOT NULL DEFAULT 0,
    BanReason TEXT NOT NULL DEFAULT '',
    CreatedUtc TEXT NOT NULL,
    LastSeenUtc TEXT NULL
);

CREATE TABLE IF NOT EXISTS Activity(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Action TEXT NOT NULL,
    CreatedUtc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Downloads(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    FileName TEXT NOT NULL,
    Url TEXT NOT NULL,
    SizeBytes INTEGER NOT NULL DEFAULT 0,
    CreatedUtc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Notifications(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Title TEXT NOT NULL,
    Message TEXT NOT NULL,
    IsRead INTEGER NOT NULL DEFAULT 0,
    CreatedUtc TEXT NOT NULL
);
